name = Two Column Content
description = The default Page layout for Basis theme.
preview = preview.png
template = basis-2-col-layout

; Regions
regions[header]         = Header
regions[branding]     = Branding
regions[preface]     = Preface
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar] = Sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/basis-2-col/basis-2-col.layout.css
