name = Single Column Content
description = The default Article layout for Basis theme.
preview = preview.png
template = basis-layout

; Regions
regions[header]         = Header
regions[branding]     = Branding
regions[preface]     = Preface
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/basis/basis.layout.css
